#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gjs
Version  : 1.46.0
Release  : 3
URL      : https://download.gnome.org/core/3.22/3.22.0/sources/gjs-1.46.0.tar.xz
Source0  : https://download.gnome.org/core/3.22/3.22.0/sources/gjs-1.46.0.tar.xz
Summary  : Internal API for gjs (for modules and embedders); uses mozjs
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0 MIT
Requires: gjs-bin
Requires: gjs-lib
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : mozjs-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(cairo-xlib)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : readline-dev

%description
This module contains JavaScript bindings based on gobject-introspection.
Because JavaScript is pretty free-form, consistent coding style and unit tests
are critical to give it some structure and keep it readable.
We propose that all GNOME usage of JavaScript conform to the style guide
in doc/Style_Guide.txt to help keep things sane.

%package bin
Summary: bin components for the gjs package.
Group: Binaries

%description bin
bin components for the gjs package.


%package dev
Summary: dev components for the gjs package.
Group: Development
Requires: gjs-lib
Requires: gjs-bin
Provides: gjs-devel

%description dev
dev components for the gjs package.


%package lib
Summary: lib components for the gjs package.
Group: Libraries

%description lib
lib components for the gjs package.


%prep
%setup -q -n gjs-1.46.0

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/gjs/girepository-1.0/GjsPrivate-1.0.typelib

%files bin
%defattr(-,root,root,-)
/usr/bin/gjs
/usr/bin/gjs-console

%files dev
%defattr(-,root,root,-)
/usr/include/gjs-1.0/gi/arg.h
/usr/include/gjs-1.0/gi/boxed.h
/usr/include/gjs-1.0/gi/closure.h
/usr/include/gjs-1.0/gi/enumeration.h
/usr/include/gjs-1.0/gi/foreign.h
/usr/include/gjs-1.0/gi/function.h
/usr/include/gjs-1.0/gi/fundamental.h
/usr/include/gjs-1.0/gi/gerror.h
/usr/include/gjs-1.0/gi/gtype.h
/usr/include/gjs-1.0/gi/interface.h
/usr/include/gjs-1.0/gi/keep-alive.h
/usr/include/gjs-1.0/gi/ns.h
/usr/include/gjs-1.0/gi/object.h
/usr/include/gjs-1.0/gi/param.h
/usr/include/gjs-1.0/gi/repo.h
/usr/include/gjs-1.0/gi/union.h
/usr/include/gjs-1.0/gi/value.h
/usr/include/gjs-1.0/gjs/byteArray.h
/usr/include/gjs-1.0/gjs/compat.h
/usr/include/gjs-1.0/gjs/context.h
/usr/include/gjs-1.0/gjs/coverage.h
/usr/include/gjs-1.0/gjs/gjs-module.h
/usr/include/gjs-1.0/gjs/gjs.h
/usr/include/gjs-1.0/gjs/importer.h
/usr/include/gjs-1.0/gjs/jsapi-util.h
/usr/include/gjs-1.0/gjs/mem.h
/usr/include/gjs-1.0/gjs/native.h
/usr/include/gjs-1.0/gjs/runtime.h
/usr/include/gjs-1.0/gjs/type-module.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
